# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - apt upgrade && apt update && apt -y install make autoconf default-jre
    - java --version
  script:
    - cd ./Algorithms/Mergesort/
    - chmod +x ./Sonar/build-wrapper-linux-x86/build-wrapper-linux-x86-64 && chmod +x ./Sonar/sonar-scanner-4.3.0.2102-linux/bin/sonar-scanner
    - chmod +x ExecSonarLinux.sh && ./ExecSonarLinux.sh
  artifacts:
    paths:
      - main
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

